---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Spot Instances Auto-Deregister from ECS Cluster'

Parameters:

  ecsClusterName:
    Type: String
    Default: default
    Description: Target ECS Cluster Name.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "ECS Configuration"
        Parameters:
          - ecsClusterName

Resources:

  ecsTaskRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ecs-tasks.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "DeregisterContainerInstance"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "ecs:DeregisterContainerInstance"
                Resource: arn:aws:ecs:*:*:cluster/*"

  ecsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-TaskDefinition
      TaskRoleArn: !Ref ecsTaskRole
      RequiresCompatibilities: ["EC2"]
      NetworkMode: "host"
      ContainerDefinitions: 
        -
          Name: "ecs-spot-agent"
          Image: "mats16/ecs-spot-agent"
          Cpu: "10"
          Memory: "100"
          Essential: "true"

  ecsService: 
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref ecsClusterName
      LaunchType: "EC2"
      SchedulingStrategy: "DAEMON"
      TaskDefinition: !Ref ecsTaskDefinition

